config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :cart_items
  resources :carts
  resources :items
  resources :orders
  resources :customers
  resources :stores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "stores#index"
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :orders
  validates :name, :address, presence: true
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :description, :address)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= store.description %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= store.address %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<h1>Lojas</h1>
<%= link_to 'Nova Loja', new_store_path, class: 'btn btn-primary mb-3' %>
<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Endereço</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.description %></td>
        <td><%= store.address %></td>
        <td><%= link_to 'Mostrar', store, class: 'btn btn-secondary' %></td>
        <td><%= link_to 'Editar', edit_store_path(store), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Excluir', store, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<h1><%= @store.name %></h1>
<p><%= @store.description %></p>
<p><%= @store.address %></p>
<%= link_to 'Editar', edit_store_path(@store), class: 'btn btn-warning' %>
<%= link_to 'Voltar', stores_path, class: 'btn btn-secondary' %>