config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :cart_items
  resources :carts
  resources :items
  resources :orders
  resources :customers
  resources :stores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "stores#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  has_many :cart_items
  has_many :items, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy!

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:customer_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
  <p>
    <strong>Customer:</strong>
    <%= cart.customer_id %>
  </p>

</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customer_id, style: "display: block" %>
    <%= form.text_field :customer_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<h1>Carrinhos</h1>
<%= link_to 'Novo Carrinho', new_cart_path, class: 'btn btn-primary mb-3' %>
<table class="table">
  <thead>
    <tr>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.customer.name %></td>
        <td><%= link_to 'Mostrar', cart, class: 'btn btn-secondary' %></td>
        <td><%= link_to 'Editar', edit_cart_path(cart), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Excluir', cart, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<h1>Carrinho do Cliente <%= @cart.customer.name %></h1>
<h3>Itens</h3>
<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Quantidade</th>
      <th>Preço</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.cart_items.each do |item| %>
      <tr>
        <td><%= item.item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.item.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Editar', edit_cart_path(@cart), class: 'btn btn-warning' %>
<%= link_to 'Voltar', carts_path, class: 'btn btn-secondary' %>