config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :cart_items
  resources :carts
  resources :items
  resources :orders
  resources :customers
  resources :stores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "stores#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LojaappRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">LojaApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Lojas', stores_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Clientes', customers_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Pedidos', orders_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Itens', items_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Carrinhos', carts_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>